name: Python CI - Baseline

on: [push]

jobs:
  baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      
          
      #baseline dependencies
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r package1/requirements.txt || true
          python -m pip install -r package2/requirements.txt || true
          python -m pip install -r package3/requirements.txt || true
          python -m pip install pytest

      - name: Run tests
        run: |
          python -m pytest package1/tests
          python -m pytest package2/tests
          python -m pytest package3/tests
  containerized-caching:
    runs-on: ubuntu-latest
    needs: baseline 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-container-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-container-
      - name: Build Docker image
        run: docker build -t ci-cd-calc .

      - name: Run tests inside container
        run: docker run ci-cd-calc


 
          


