name: Python CI - Baseline

on: [push]

jobs:
  ##baseline:

  #package 1 tests
  package1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      
          
      #baseline dependencies
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r package1/requirements.txt || true
          python -m pip install pytest

      - name: Run package1 tests
        run: |
          python -m pytest package1/tests


  #package 2 tests
  package2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      
          
      #baseline dependencies
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r package2/requirements.txt || true
          python -m pip install pytest

      - name: Run package2 tests
        run: |
          python -m pytest package2/tests
  
  #package 3 tests
  package3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      
          
      #baseline dependencies
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r package3/requirements.txt || true
          python -m pip install pytest

      - name: Run package3 tests
        run: |
          python -m pytest package3/tests
          


